export type IntegrationCategory =
  | 'analytics'
  | 'ppc'
  | 'seo'
  | 'social'
  | 'email'
  | 'call-tracking'
  | 'ecommerce'
  | 'local'
  | 'database'
  | 'all';

export interface Integration {
  id: string;
  name: string;
  description: string;
  logo: string;
  categories: IntegrationCategory[];
  isConfigured?: boolean;
  status?: 'connected' | 'disconnected' | 'error';
}

// Collection of all integrations
export const integrations: Integration[] = [
  {
    id: 'activecampaign',
    name: 'ActiveCampaign',
    description: 'Email marketing automation',
    logo: 'https://ext.same-assets.com/1044981387/activecampaign.svg',
    categories: ['email'],
  },
  {
    id: 'adroll',
    name: 'AdRoll',
    description: 'Retargeting and display ads',
    logo: 'https://ext.same-assets.com/1044981387/adroll.svg',
    categories: ['ppc'],
  },
  {
    id: 'adform',
    name: 'Adform',
    description: 'Digital advertising platform',
    logo: 'https://ext.same-assets.com/1044981387/adform.svg',
    categories: ['ppc'],
  },
  {
    id: 'ahrefs',
    name: 'Ahrefs',
    description: 'SEO & backlink analysis',
    logo: 'https://ext.same-assets.com/1044981387/ahrefs.svg',
    categories: ['seo'],
  },
  {
    id: 'amazon-ads',
    name: 'Amazon Ads',
    description: 'Amazon advertising platform',
    logo: 'https://ext.same-assets.com/1044981387/amazon-ads.svg',
    categories: ['ppc', 'ecommerce'],
  },
  {
    id: 'amazon-redshift',
    name: 'Amazon Redshift',
    description: 'Cloud data warehouse',
    logo: 'https://ext.same-assets.com/1044981387/amazon-redshift.svg',
    categories: ['database'],
  },
  {
    id: 'avanser',
    name: 'Avanser',
    description: 'Call tracking and analytics',
    logo: 'https://ext.same-assets.com/1044981387/avanser.svg',
    categories: ['call-tracking'],
  },
  {
    id: 'backlink-manager',
    name: 'Backlink Manager',
    description: 'Backlink monitoring',
    logo: 'https://ext.same-assets.com/1044981387/backlink-manager.svg',
    categories: ['seo'],
  },
  {
    id: 'basis-platform',
    name: 'Basis Platform',
    description: 'Digital marketing platform',
    logo: 'https://ext.same-assets.com/1044981387/basis.svg',
    categories: ['ppc'],
  },
  {
    id: 'basis-standalone-dsp',
    name: 'Basis Standalone DSP',
    description: 'Demand-side platform',
    logo: 'https://ext.same-assets.com/1044981387/basis.svg',
    categories: ['ppc'],
  },
  {
    id: 'bigcommerce',
    name: 'BigCommerce',
    description: 'E-commerce platform',
    logo: 'https://ext.same-assets.com/1044981387/bigcommerce.svg',
    categories: ['ecommerce'],
  },
  {
    id: 'bing-webmaster-tools',
    name: 'Bing Webmaster Tools',
    description: 'Search performance tool',
    logo: 'https://ext.same-assets.com/1044981387/bing-webmaster.svg',
    categories: ['seo'],
  },
  {
    id: 'birdeye',
    name: 'BirdEye',
    description: 'Customer experience platform',
    logo: 'https://ext.same-assets.com/1044981387/birdeye.svg',
    categories: ['local'],
  },
  {
    id: 'brevo',
    name: 'Brevo',
    description: 'Email marketing platform',
    logo: 'https://ext.same-assets.com/1044981387/brevo.svg',
    categories: ['email'],
  },
  {
    id: 'brightlocal',
    name: 'BrightLocal',
    description: 'Local SEO tool',
    logo: 'https://ext.same-assets.com/1044981387/brightlocal.svg',
    categories: ['local', 'seo'],
  },
  {
    id: 'callrail',
    name: 'CallRail',
    description: 'Call tracking and analytics',
    logo: 'https://ext.same-assets.com/1044981387/callrail.svg',
    categories: ['call-tracking'],
  },
  {
    id: 'callsource',
    name: 'CallSource',
    description: 'Call tracking platform',
    logo: 'https://ext.same-assets.com/1044981387/callsource.svg',
    categories: ['call-tracking'],
  },
  {
    id: 'calltrackingmetrics',
    name: 'CallTrackingMetrics',
    description: 'Call analytics platform',
    logo: 'https://ext.same-assets.com/1044981387/calltrackingmetrics.svg',
    categories: ['call-tracking'],
  },
  {
    id: 'campaign-monitor',
    name: 'Campaign Monitor',
    description: 'Email marketing service',
    logo: 'https://ext.same-assets.com/1044981387/campaign-monitor.svg',
    categories: ['email'],
  },
  {
    id: 'choozle',
    name: 'Choozle',
    description: 'Digital advertising platform',
    logo: 'https://ext.same-assets.com/1044981387/choozle.svg',
    categories: ['ppc'],
  },
  {
    id: 'constant-contact',
    name: 'Constant Contact',
    description: 'Email marketing platform',
    logo: 'https://ext.same-assets.com/1044981387/constant-contact.svg',
    categories: ['email'],
  },
  {
    id: 'convertkit',
    name: 'ConvertKit',
    description: 'Creator-focused email platform',
    logo: 'https://ext.same-assets.com/1044981387/convertkit.svg',
    categories: ['email'],
  },
  {
    id: 'delacon',
    name: 'Delacon',
    description: 'Call tracking solution',
    logo: 'https://ext.same-assets.com/1044981387/delacon.svg',
    categories: ['call-tracking'],
  },
  {
    id: 'drip',
    name: 'Drip',
    description: 'E-commerce CRM platform',
    logo: 'https://ext.same-assets.com/1044981387/drip.svg',
    categories: ['email', 'ecommerce'],
  },
  {
    id: 'facebook',
    name: 'Facebook',
    description: 'Social media platform',
    logo: 'https://ext.same-assets.com/1044981387/3251570025.svg',
    categories: ['social'],
    status: 'connected',
    isConfigured: true,
  },
  {
    id: 'facebook-ads',
    name: 'Facebook Ads',
    description: 'Social media advertising',
    logo: 'https://ext.same-assets.com/1044981387/2265610738.svg',
    categories: ['social', 'ppc'],
    status: 'connected',
    isConfigured: true,
  },
  {
    id: 'gatherup',
    name: 'GatherUp',
    description: 'Customer experience platform',
    logo: 'https://ext.same-assets.com/1044981387/gatherup.svg',
    categories: ['local'],
  },
  {
    id: 'google-ad-manager',
    name: 'Google Ad Manager',
    description: 'Ad management platform',
    logo: 'https://ext.same-assets.com/1044981387/google-ad-manager.svg',
    categories: ['ppc'],
  },
  {
    id: 'google-ads',
    name: 'Google Ads',
    description: 'PPC advertising platform',
    logo: 'https://ext.same-assets.com/1044981387/4263905291.svg',
    categories: ['ppc'],
    status: 'connected',
    isConfigured: true,
  },
  {
    id: 'google-analytics-4',
    name: 'Google Analytics 4',
    description: 'Web analytics platform',
    logo: 'https://ext.same-assets.com/1044981387/2818150891.svg',
    categories: ['analytics'],
    status: 'connected',
    isConfigured: true,
  },
  {
    id: 'google-bigquery',
    name: 'Google BigQuery',
    description: 'Cloud data warehouse',
    logo: 'https://ext.same-assets.com/1044981387/google-bigquery.svg',
    categories: ['database'],
  },
  {
    id: 'google-business-profile',
    name: 'Google Business Profile',
    description: 'Business listing management',
    logo: 'https://ext.same-assets.com/1044981387/2338669436.svg',
    categories: ['local'],
    status: 'connected',
    isConfigured: true,
  },
  {
    id: 'google-display-video-360',
    name: 'Google Display & Video 360',
    description: 'Display advertising',
    logo: 'https://ext.same-assets.com/1044981387/google-dv360.svg',
    categories: ['ppc'],
  },
  {
    id: 'google-lighthouse',
    name: 'Google Lighthouse',
    description: 'Website performance tool',
    logo: 'https://ext.same-assets.com/1044981387/google-lighthouse.svg',
    categories: ['analytics', 'seo'],
  },
  {
    id: 'google-local-services-ads',
    name: 'Google Local Services Ads',
    description: 'Local service advertising',
    logo: 'https://ext.same-assets.com/1044981387/google-local-services.svg',
    categories: ['local', 'ppc'],
    status: 'connected',
    isConfigured: true,
  },
  {
    id: 'google-pagespeed',
    name: 'Google PageSpeed',
    description: 'Page performance metrics',
    logo: 'https://ext.same-assets.com/1044981387/google-pagespeed.svg',
    categories: ['analytics', 'seo'],
  },
  {
    id: 'google-search-console',
    name: 'Google Search Console',
    description: 'Search performance tracking',
    logo: 'https://ext.same-assets.com/1044981387/3162334539.svg',
    categories: ['seo'],
    status: 'connected',
    isConfigured: true,
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    description: 'Spreadsheet application',
    logo: 'https://ext.same-assets.com/1044981387/google-sheets.svg',
    categories: ['database'],
  },
  {
    id: 'grade-us',
    name: 'Grade.us',
    description: 'Review management platform',
    logo: 'https://ext.same-assets.com/1044981387/grade-us.svg',
    categories: ['local'],
  },
  {
    id: 'gravity-forms',
    name: 'Gravity Forms',
    description: 'WordPress form builder',
    logo: 'https://ext.same-assets.com/1044981387/gravity-forms.svg',
    categories: ['analytics'],
  },
  {
    id: 'highlevel',
    name: 'HighLevel',
    description: 'Marketing platform',
    logo: 'https://ext.same-assets.com/1044981387/highlevel.svg',
    categories: ['email', 'analytics'],
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'Marketing & CRM platform',
    logo: 'https://ext.same-assets.com/1044981387/hubspot.svg',
    categories: ['email', 'analytics'],
  },
  {
    id: 'instagram',
    name: 'Instagram',
    description: 'Social media platform',
    logo: 'https://ext.same-assets.com/1044981387/2408180683.svg',
    categories: ['social'],
  },
  {
    id: 'invoca',
    name: 'Invoca',
    description: 'Call tracking and analytics',
    logo: 'https://ext.same-assets.com/1044981387/invoca.svg',
    categories: ['call-tracking'],
  },
  {
    id: 'keap',
    name: 'Keap',
    description: 'CRM & marketing automation',
    logo: 'https://ext.same-assets.com/1044981387/keap.svg',
    categories: ['email'],
  },
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    description: 'Email marketing platform',
    logo: 'https://ext.same-assets.com/1044981387/klaviyo.svg',
    categories: ['email', 'ecommerce'],
    status: 'connected',
    isConfigured: true,
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    description: 'Professional social network',
    logo: 'https://ext.same-assets.com/1044981387/3715260105.svg',
    categories: ['social'],
  },
  {
    id: 'linkedin-ads',
    name: 'LinkedIn Ads',
    description: 'Professional network ads',
    logo: 'https://ext.same-assets.com/1044981387/linkedin-ads.svg',
    categories: ['social', 'ppc'],
  },
  {
    id: 'mailchimp',
    name: 'MailChimp',
    description: 'Email marketing service',
    logo: 'https://ext.same-assets.com/1044981387/3102595292.svg',
    categories: ['email'],
  },
  {
    id: 'majestic',
    name: 'Majestic',
    description: 'Backlink analysis tool',
    logo: 'https://ext.same-assets.com/1044981387/majestic.svg',
    categories: ['seo'],
  },
  {
    id: 'marchex',
    name: 'Marchex',
    description: 'Call analytics platform',
    logo: 'https://ext.same-assets.com/1044981387/marchex.svg',
    categories: ['call-tracking'],
  },
  {
    id: 'matomo',
    name: 'Matomo',
    description: 'Web analytics platform',
    logo: 'https://ext.same-assets.com/1044981387/matomo.svg',
    categories: ['analytics'],
  },
  {
    id: 'microsoft-advertising',
    name: 'Microsoft Advertising',
    description: 'Search advertising platform',
    logo: 'https://ext.same-assets.com/1044981387/microsoft-ads.svg',
    categories: ['ppc'],
  },
  {
    id: 'moz',
    name: 'Moz',
    description: 'SEO software suite',
    logo: 'https://ext.same-assets.com/1044981387/moz.svg',
    categories: ['seo'],
  },
  {
    id: 'mysql',
    name: 'MySQL',
    description: 'Database management system',
    logo: 'https://ext.same-assets.com/1044981387/mysql.svg',
    categories: ['database'],
  },
  {
    id: 'phonewagon',
    name: 'PhoneWagon',
    description: 'Call tracking software',
    logo: 'https://ext.same-assets.com/1044981387/phonewagon.svg',
    categories: ['call-tracking'],
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    description: 'Visual discovery platform',
    logo: 'https://ext.same-assets.com/1044981387/pinterest.svg',
    categories: ['social'],
  },
  {
    id: 'pinterest-ads',
    name: 'Pinterest Ads',
    description: 'Visual discovery ads',
    logo: 'https://ext.same-assets.com/1044981387/pinterest-ads.svg',
    categories: ['social', 'ppc'],
  },
  {
    id: 'rank-tracker',
    name: 'Rank Tracker',
    description: 'Keyword position tracking',
    logo: 'https://ext.same-assets.com/1044981387/rank-tracker.svg',
    categories: ['seo'],
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    description: 'CRM platform',
    logo: 'https://ext.same-assets.com/1044981387/salesforce.svg',
    categories: ['analytics'],
  },
  {
    id: 'semrush-backlinks',
    name: 'Semrush - Backlinks',
    description: 'Backlink analytics',
    logo: 'https://ext.same-assets.com/1044981387/2370537711.svg',
    categories: ['seo'],
  },
  {
    id: 'semrush-projects',
    name: 'Semrush - Projects',
    description: 'SEO project management',
    logo: 'https://ext.same-assets.com/1044981387/2370537711.svg',
    categories: ['seo'],
  },
  {
    id: 'servicetitan',
    name: 'ServiceTitan',
    description: 'Field service software',
    logo: 'https://ext.same-assets.com/1044981387/servicetitan.svg',
    categories: ['analytics'],
  },
  {
    id: 'sharpspring',
    name: 'SharpSpring',
    description: 'Marketing automation platform',
    logo: 'https://ext.same-assets.com/1044981387/sharpspring.svg',
    categories: ['email'],
  },
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'E-commerce platform',
    logo: 'https://ext.same-assets.com/1044981387/2207015219.svg',
    categories: ['ecommerce'],
  },
  {
    id: 'simplifi',
    name: 'Simpli.fi',
    description: 'Programmatic advertising',
    logo: 'https://ext.same-assets.com/1044981387/simplifi.svg',
    categories: ['ppc'],
  },
  {
    id: 'snapchat-ads',
    name: 'Snapchat Ads',
    description: 'Social media advertising',
    logo: 'https://ext.same-assets.com/1044981387/snapchat-ads.svg',
    categories: ['social', 'ppc'],
  },
  {
    id: 'spotify-ads',
    name: 'Spotify Ads',
    description: 'Audio advertising platform',
    logo: 'https://ext.same-assets.com/1044981387/spotify-ads.svg',
    categories: ['ppc'],
  },
  {
    id: 'stackadapt',
    name: 'StackAdapt',
    description: 'Programmatic advertising',
    logo: 'https://ext.same-assets.com/1044981387/stackadapt.svg',
    categories: ['ppc'],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Payment processing platform',
    logo: 'https://ext.same-assets.com/1044981387/stripe.svg',
    categories: ['analytics', 'ecommerce'],
  },
  {
    id: 'synup',
    name: 'Synup',
    description: 'Listing management platform',
    logo: 'https://ext.same-assets.com/1044981387/synup.svg',
    categories: ['local'],
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    description: 'Video sharing platform',
    logo: 'https://ext.same-assets.com/1044981387/tiktok.svg',
    categories: ['social'],
  },
  {
    id: 'tiktok-ads',
    name: 'TikTok Ads',
    description: 'Video platform advertising',
    logo: 'https://ext.same-assets.com/1044981387/tiktok-ads.svg',
    categories: ['social', 'ppc'],
  },
  {
    id: 'trustpilot',
    name: 'Trustpilot',
    description: 'Review platform',
    logo: 'https://ext.same-assets.com/1044981387/trustpilot.svg',
    categories: ['local'],
  },
  {
    id: 'twilio',
    name: 'Twilio',
    description: 'Communication API platform',
    logo: 'https://ext.same-assets.com/1044981387/twilio.svg',
    categories: ['analytics'],
  },
  {
    id: 'unbounce',
    name: 'Unbounce',
    description: 'Landing page builder',
    logo: 'https://ext.same-assets.com/1044981387/unbounce.svg',
    categories: ['analytics'],
  },
  {
    id: 'vendasta',
    name: 'Vendasta',
    description: 'Business platform',
    logo: 'https://ext.same-assets.com/1044981387/vendasta.svg',
    categories: ['local'],
  },
  {
    id: 'vimeo',
    name: 'Vimeo',
    description: 'Video hosting platform',
    logo: 'https://ext.same-assets.com/1044981387/vimeo.svg',
    categories: ['social'],
  },
  {
    id: 'whatconverts',
    name: 'WhatConverts',
    description: 'Lead tracking platform',
    logo: 'https://ext.same-assets.com/1044981387/whatconverts.svg',
    categories: ['analytics'],
  },
  {
    id: 'wildjar',
    name: 'WildJar',
    description: 'Call tracking platform',
    logo: 'https://ext.same-assets.com/1044981387/wildjar.svg',
    categories: ['call-tracking'],
  },
  {
    id: 'woocommerce',
    name: 'WooCommerce',
    description: 'E-commerce for WordPress',
    logo: 'https://ext.same-assets.com/1044981387/woocommerce.svg',
    categories: ['ecommerce'],
  },
  {
    id: 'x-ads',
    name: 'X Ads',
    description: 'Twitter advertising platform',
    logo: 'https://ext.same-assets.com/1044981387/3092986003.svg',
    categories: ['social', 'ppc'],
  },
  {
    id: 'yelp',
    name: 'Yelp',
    description: 'Business directory service',
    logo: 'https://ext.same-assets.com/1044981387/yelp.svg',
    categories: ['local'],
  },
  {
    id: 'yelp-ads',
    name: 'Yelp Ads',
    description: 'Local business advertising',
    logo: 'https://ext.same-assets.com/1044981387/yelp-ads.svg',
    categories: ['local', 'ppc'],
  },
  {
    id: 'yext',
    name: 'Yext',
    description: 'Listing management platform',
    logo: 'https://ext.same-assets.com/1044981387/yext.svg',
    categories: ['local'],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    description: 'Video platform',
    logo: 'https://ext.same-assets.com/1044981387/youtube.svg',
    categories: ['social'],
  },
];

// Helper functions for integrations
export const getIntegrationsByCategory = (category: IntegrationCategory) => {
  if (category === 'all') {
    return integrations;
  }
  return integrations.filter(integration => integration.categories.includes(category));
};

export const getIntegrationById = (id: string) => {
  return integrations.find(integration => integration.id === id);
};

export const getConnectedIntegrations = () => {
  return integrations.filter(integration => integration.status === 'connected');
};

export const categories = [
  { id: 'all', name: 'All Categories' },
  { id: 'analytics', name: 'Analytics' },
  { id: 'call-tracking', name: 'Call Tracking' },
  { id: 'database', name: 'Database' },
  { id: 'ecommerce', name: 'Ecommerce' },
  { id: 'email', name: 'Email' },
  { id: 'local', name: 'Local' },
  { id: 'ppc', name: 'PPC' },
  { id: 'seo', name: 'SEO' },
  { id: 'social', name: 'Social' },
];
