[images]
  remote_images = ["https://ext.same-assets.com/.*", "https://ext.same-assets.com/1044981387/.*"]

[build]
  command = "bun run build:ignore-ts"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
