[images]
  remote_images = ["https://ext.same-assets.com/.*", "https://ext.same-assets.com/1044981387/.*"]

[build]
  command = "npx next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_TYPESCRIPT_COMPILE_SKIP = "true"
  NEXT_SKIP_TYPE_CHECK = "true"
  ESLINT_SKIP_DIRs = "."
  GO_VERSION = "1.19.13"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
